name: Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25

      - uses: gradle/actions/setup-gradle@v6

      - run: ./gradlew chiseledBuild

      - uses: actions/upload-artifact@v7
        with:
          name: anarchymod-builds
          path: |
            versions/*/build/libs/anarchymod-mc-*.jar
            !versions/*/build/libs/anarchymod-mc-*-sources.jar
          if-no-files-found: error
